### PR TITLE
Unified QR response

### PR DESCRIPTION
**Pull request by Sak1012**
This PR tries to Solve Issue #191 (Integrate Check-in and Lead Scanning into a Single QR Code)

Since both the codes are generated on a order they are now embedded into a single QR in the following json format

```json
{
  "ticket": "5uhbd49wms2fakafn5nzq7pcqpbjun2v",
  "lead": "PZD97WTMFJ"
}
```

## Summary by Sourcery

Unify the QR code generation by embedding both the ticket and lead information into a single JSON object, allowing for integrated check-in and lead scanning functionality.

New Features:
- Integrate check-in and lead scanning into a single QR code by embedding both codes into a unified JSON format.

### CODE REVIEW

**Comment by cweitat** [comment]
I would recommend to have event id or something for scanner to check for validity locally first before calling for server.

**Comment by Sak1012** [comment]
This PR focuses on unifying two QR codes into one. In Open Event Checkin, the QR code will only be scanned after the device is authenticated and the event is selected for check-in. Once the device is authenticated, the list of events becomes available to the scanner.

Could you please clarify how incorporating the event ID for local validity checks before calling the server might work with this process?

**Comment by cweitat** [comment]
@Sak1012 assuming there's no eventid to reference the selected event to scan, every request, even those qr without the right keys, gets sent to the server which are unwanted. If you have 10,000 devices sending json to server for checks, with and without ticket id field, do you think there will be a bottleneck on the server from returning "ticket key not found" / "ticket is not for this event" kind of error?

**Comment by Sak1012** [comment]
I have modified it so that it now includes the eventname. The response would now look like

```json
{
  "event": "EventName",
  "ticket": "5uhbd49wms2fakafn5nzq7pcqpbjun2v",
  "lead": "PZD97WTMFJ"
}
```

**Comment by cweitat** [comment]
> I have modified it so that it now includes the eventname. The response would now look like
> 
> ```json
> {
>   "event": "EventName",
>   "ticket": "5uhbd49wms2fakafn5nzq7pcqpbjun2v",
>   "lead": "PZD97WTMFJ"
> }
> ```

this is based on the assumption that no event name are equal under the same account. will you have checks on the event creation side that no dup names exist?

**Comment by mariobehling** [comment]
I think it would be better to use a unique event-ID.

**Comment by Sak1012** [comment]
Since there is no particular "event_id" for events in eventyay-tickets can `event-slug` and `organiser` be used instead, as they are unique values and by checking both of them it can be made sure it's unique and accurate for the particular event before sending the request to the server.

So the embedded data would look like
```json
{
  "event": "event_slug",
  "org": "organiser",
  "ticket": "5uhbd49wms2fakafn5nzq7pcqpbjun2v",
  "lead": "PZD97WTMFJ"
}
```

**Pull request merged**
