### PR TITLE
convert build setup to pyproject.toml

### PR DESCRIPTION
**Pull request by eMBee**
this is a significant restructuring of the build process. resubmit of PR #59

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
We now have a docker build test. This PR fails in the docker build.

**Comment by eMBee** [comment]
rebased the PR on latest development.

**Comment by marcoag** [comment]
Tested using the new [workflow to build and deploy any commit ](https://github.com/fossasia/eventyay-tickets/pull/114), it seems to work ATM on https://tickets-dev.eventyay.com/.

@eMBee for clarity and history prevalence it would be better if you don't force push unless necessary and if you do adding a comment on the reasoning so we don't miss information. It's hard to understand reviews when force-pushes happen.

**Review by marcoag — APPROVED** [review]

**Comment by marcoag** [comment]
Also this PR has unrelated changes like modifications to workflows, not sure how those are related to pryproject.toml. Will go ahead and merge anyway but let's try to keep future PRs scoped.

**Pull request merged**
