### PR TITLE
change the theme of loading-modal

### LINKED ISSUE #230: Change the loading icon and improve message
The loading icon should be updated to a more modern option.

Screenshot from 2024-07-06 00-00-13

Also change the text to the following:

```
Processing Your Request

Hang tight! If it takes more than a minute, please check your internet connection and refresh the page.
```

### PR DESCRIPTION
**Pull request by AviGawande**
fixes #230
attached screenshots:

## Summary by Sourcery

This pull request updates the theme of the loading modal by replacing the cog icon with a spinner icon and enhancing the layout and styling for improved alignment and responsiveness.

- **Enhancements**:
    - Updated the loading modal theme to use a spinner icon instead of a cog icon.
    - Improved the layout and styling of the loading modal for better alignment and responsiveness.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please add screenshots. Thanks.

**Comment by AviGawande** [comment]
Screenshot (82)

**Comment by mariobehling** [comment]
Please do not change transparency and design. Only change the icon and text as described in the issue. Thanks.

**Comment by mariobehling** [comment]
Please provide screenshots and resolve conflicts.

**Comment by AviGawande** [comment]
Screenshot (93)
if required we can change to other design

**Comment by mariobehling** [comment]
This is missing the text change mentioned in the issue.

**Comment by AviGawande** [comment]
@mariobehling solved,it was port issue,everything is working fine
Screenshot (95)

**Comment by mariobehling** [comment]
@sourcery-ai review

**Pull request closed without merging**
