### PR TITLE
Update Django to Version 3.2

### PR DESCRIPTION
**Pull request by norbusan**
Extends PR https://github.com/fossasia/eventyay-tickets/pull/98

To be done:

# System check warnings

```
eventyay-tickets  | System check identified some issues:
eventyay-tickets  | 
eventyay-tickets  | WARNINGS:
eventyay-tickets  | badges.BadgeItem: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
eventyay-tickets  |     HINT: Configure the DEFAULT_AUTO_FIELD setting or the BadgesApp.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
eventyay-tickets  | badges.BadgeLayout: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
eventyay-tickets  |     HINT: Configure the DEFAULT_AUTO_FIELD setting or the BadgesApp.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
eventyay-tickets  | banktransfer.BankImportJob: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
eventyay-tickets  |     HINT: Configure the DEFAULT_AUTO_FIELD setting or the BankTransferApp.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
eventyay-tickets  | banktransfer.BankTransaction: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
eventyay-tickets  |     HINT: Configure the DEFAULT_AUTO_FIELD setting or the BankTransferApp.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
eventyay-tickets  | banktransfer.RefundExport: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
eventyay-tickets  |     HINT: Configure the DEFAULT_AUTO_FIELD setting or the BankTransferApp.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
..... MANY MORE
```

# Runtime errors due to integrity issues

```
eventyay-tickets  | Running migrations:
eventyay-tickets  | Traceback (most recent call last):
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
eventyay-tickets  |     return self.cursor.execute(sql)
eventyay-tickets  | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
eventyay-tickets  | DETAIL:  Key (typname, typnamespace)=(django_migrations_id_seq, 2200) already exists.
eventyay-tickets  | 
eventyay-tickets  | 
eventyay-tickets  | The above exception was the direct cause of the following exception:
eventyay-tickets  | 
eventyay-tickets  | Traceback (most recent call last):
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 68, in ensure_schema
eventyay-tickets  |     editor.create_model(self.Migration)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 345, in create_model
eventyay-tickets  |     self.execute(sql, params or None)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
eventyay-tickets  |     cursor.execute(sql, params)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
eventyay-tickets  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
eventyay-tickets  |     return executor(sql, params, many, context)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
eventyay-tickets  |     return self.cursor.execute(sql, params)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
eventyay-tickets  |     raise dj_exc_value.with_traceback(traceback) from exc_value
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
eventyay-tickets  |     return self.cursor.execute(sql)
eventyay-tickets  | django.db.utils.IntegrityError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
eventyay-tickets  | DETAIL:  Key (typname, typnamespace)=(django_migrations_id_seq, 2200) already exists.
eventyay-tickets  | 
eventyay-tickets  | 
eventyay-tickets  | During handling of the above exception, another exception occurred:
eventyay-tickets  | 
eventyay-tickets  | Traceback (most recent call last):
eventyay-tickets  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
eventyay-tickets  |     return _run_code(code, main_globals, None,
eventyay-tickets  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
eventyay-tickets  |     exec(code, run_globals)
eventyay-tickets  |   File "/pretix/src/pretix/__main__.py", line 9, in <module>
eventyay-tickets  |     execute_from_command_line(sys.argv)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
eventyay-tickets  |     utility.execute()
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
eventyay-tickets  |     self.fetch_command(subcommand).run_from_argv(self.argv)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
eventyay-tickets  |     self.execute(*args, **cmd_options)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
eventyay-tickets  |     output = self.handle(*args, **options)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
eventyay-tickets  |     res = handle_func(*args, **kwargs)
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
eventyay-tickets  |     post_migrate_state = executor.migrate(
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 91, in migrate
eventyay-tickets  |     self.recorder.ensure_schema()
eventyay-tickets  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
eventyay-tickets  |     raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
eventyay-tickets  | django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
eventyay-tickets  | DETAIL:  Key (typname, typnamespace)=(django_migrations_id_seq, 2200) already exists.
eventyay-tickets  | )
```

But I could
* log into the container and create a superuser
* log into the website and configure a bit

I did not try creating events etc.

### CODE REVIEW

**Comment by mariobehling** [comment]
@norbusan @marcoag @hongquan Should this PR get merged and we engage the other contributors to help to solve the issues? This could speed up the development process.

**Review by marcoag — APPROVED** [review]

**Review by marcoag — CHANGES_REQUESTED** [review]
Can we cherry pick the last two commits?

It might also be good if we can pass tests, any gsoc student wanna have a look? this could be a good simple task.

**Comment by mariobehling** [comment]
Yes, to cherry-pick. Could you go ahead and do it, please?

**Comment by progmatic-99** [comment]
@marcoag @mariobehling  looking into it

**Comment by untari** [comment]
@progmatic-99 Since this seems urgent, I cherry-picked already in:  [https://github.com/fossasia/eventyay-tickets/pull/104](url) so we can move forward.

**Comment by norbusan** [comment]
Closing this since #104 has been merged.

**Pull request closed without merging**
