### PR TITLE
Update Paypal to a more recent version

### PR DESCRIPTION
**Pull request by lcduong**
> Fixes [#151  Update Paypal to a more recent version](https://github.com/fossasia/eventyay-tickets/issues/151)
> 
> #### Short description of what this resolves:
> Update Paypal to a more recent version
> 
> #### Changes proposed in this pull request:
> * Update Paypal to a more recent version
> 
> #### Checklist
> * [x]  I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
> * [x]  My branch is up-to-date with the Upstream `development` branch.
> * [ ]  The acceptance, integration, unit tests and linter pass locally with my changes
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  I have added necessary documentation (if appropriate)

## Summary by Sourcery

This pull request updates the PayPal integration to a more recent version, incorporating the latest PayPal SDKs and APIs. It introduces support for PayPal Alternative Payment Methods (APM), enhances the configuration interface, and improves error handling and logging. The user interface for PayPal payment options has also been enhanced to dynamically render available payment methods.

- **New Features**:
    - Introduced support for PayPal Alternative Payment Methods (APM) including various local payment methods.
    - Added a new PayPal payment method configuration interface with enhanced settings and options.
    - Implemented a new PayPal payment flow using the PayPal Checkout SDK.
- **Enhancements**:
    - Refactored the PayPal integration to use the latest PayPal SDKs and APIs.
    - Improved error handling and logging for PayPal transactions.
    - Enhanced the user interface for PayPal payment options, including dynamic rendering of available payment methods.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please check the docker build is failing.

**Comment by mariobehling** [comment]
I cannot get it to run using docker autodeployment. Getting the following errors:

1 error and 7 warnings

- Push Docker image to Docker hub
  - buildx call failed with: ERROR: failed to solve: process "/bin/sh -c chmod +x /usr/local/bin/pretix && rm /etc/nginx/sites-enabled/default && cd /pretix/src && rm -f pretix.cfg && \tmkdir -p data && chown -R pretixuser:pretixuser /pretix /data data && \tsudo -u pretixuser make production" did not complete successfully: exit code: 2
- Push Docker image to Docker hub
  - Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9, docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- Push Docker image to Docker hub
  - The following actions uses node12 which is deprecated and will be forced to run on node16: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9, docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
- Push Docker image to Docker hub
  - The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Push Docker image to Docker hub
  - The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Push Docker image to Docker hub
  - The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Push Docker image to Docker hub
  - The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Push Docker image to Docker hub
  - The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Review by mariobehling — CHANGES_REQUESTED** [review]
This PR implements the entire Paypal API connection in the user space. Instead this should be implemented in two places - as previously.

All admin API settings should remain in control/global/settings/
* PayPal Connect: Client ID
* PayPal Connect: Secret key
* PayPal Connect Endpoint

Screenshot from 2024-06-20 13-04-52

The user area should be simple as in the open-event front (just enter an email) or the current pretix version ("connect to Paypal" option).

Screenshot from 2024-06-20 13-10-44

**Comment by lcduong** [comment]
Hi @mariobehling, this is similar case with Stripe we discussed, if admin did not config Paypal key in global setting, User must config by theirself in paypemt setting, if admin did setup key in global setting, User just will see action to connect with paypal and integrate with Paypal business account set up in global. For more clarify, please see below testing

**Testing**
_Admin did not config global key_
1. Admin did not setup public key, private key and merchant id in global setting
image
2. In payment setting of each event, User must connect with Paypal account which will be used only for that event.
image
3. place order and paid
image

_Admin has configured global key for paypal_
1. First we need a business paypal account (for testing, I'm using sandbox account)
image
note private key, public key and account id (merchant id)
image

2. set noted key in admin global setting
3. There is option connect with Paypal in payment setting for event which not configured yet
image
4. Now just follow step by step and connect with business paypal account
image

image

image

Enable payment method and start selling your tickets

image

Please ping me if any confuse.

**Comment by mariobehling** [comment]
Getting Internal Server Error when accessing the Payment options page of an event.

Screenshot from 2024-06-22 07-42-19

**Comment by mariobehling** [comment]
This server error happens after I fill in the Paypal details into the global admin settings page.

Screenshot from 2024-06-22 07-59-13

**Comment by lcduong** [comment]
> Getting Internal Server Error when accessing the Payment options page of an event.
> 

Hi @mariobehling , could you share with me the logs?

**Comment by odkhang** [comment]
Hi @mariobehling, issue is fixed, please test it again.

**Comment by mariobehling** [comment]
@lcduong I am getting 

> An error occurred during connecting with PayPal, please try again.

Screenshot from 2024-07-01 11-04-43

**Comment by mariobehling** [comment]
Could it be that you also need paypal-checkout-serversdk 1.0.* in order to get this working?

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
@sourcery-ai review

**Pull request closed without merging**
