### PR TITLE
Adapt design of ticketing pages to match talk component

### PR DESCRIPTION
**Pull request by odkhang**
This PR cover 2 issue 
 [#252 Adapt design of ticketing pages to match talk component](https://github.com/fossasia/eventyay-tickets/issues/252)
 [#253 Add menu with schedule, sessions, speakers, tickets, online link itself](https://github.com/fossasia/eventyay-tickets/issues/253)

Here is the new layout for ticket shop:

image

## Summary by Sourcery

This pull request updates the design of the ticketing pages to align with the talk component, adds a new navigation menu with links to schedule, sessions, speakers, and videos, and introduces a new template tag for fetching configuration settings. Additionally, new configuration settings for TALK_URL and VIDEO_URL have been added.

- **New Features**:
    - Added a navigation menu to the ticketing pages with links to schedule, sessions, speakers, and videos.
- **Enhancements**:
    - Updated the design of the ticketing pages to match the talk component, including changes to the header and layout.
    - Introduced a new template tag `setting_values` to fetch configuration settings in templates.
- **Build**:
    - Added new configuration settings for TALK_URL and VIDEO_URL in the settings file.

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Test screenshot looks different to your screenshot:

Screenshot from 2024-07-27 13-20-51

Please
* ensure spacing above info box is sufficient
* spacing below languages

**Comment by mariobehling** [comment]
I see https://wikimania-live.eventyay.com is hardcoded, but the platform can have different events that plug into video-component deployments using different links. Also after the current event we will change the URL of the video component. So, it is not a good idea to hardcode the link to this component. Please provide an option to add the link to the video component for the event organiser.

**Comment by mariobehling** [comment]
The video platform is only accessible if the user has a ticket. Therefore we need to ensure this is implemented in the menu bar as well. Is the following possible?
1. If the user has already purchased a ticket direct the user to the video platform including a trait token.
2. If the user does not have a ticket. Show a pop up "You need to get a ticket in order to access the video platform."

**Comment by mariobehling** [comment]
Screenshot from 2024-07-28 18-25-57

1. Missing Ticket menu item: Compared to the talk component the menu item "Tickets" is missing itself. It should be the fourth item from the left. And it should be highlighted same as the links on the eventyay-talk components.
2. Considering the questions about the video component that need to be discussed, maybe this issue can be solved in two steps. Step 1: Show the four items Schedule, Sessions, Speakers, Tickets. Step 2: Show the "Video" link. We should discuss the options here in a short call.

**Comment by odkhang** [comment]
Hi @mariobehling , layout has been updated, please help me to take a look and let me know if any feedback,

image

for the link to schedule, sesssion,... will be configured in event setting, basic tab

image


Please note that video not included the token yet

**Comment by mariobehling** [comment]
Docker build is failing.

Could you ensure that if no link is added, then the menu item should not show up.

**Comment by mariobehling** [comment]
353078412-b4bf565b-3d7f-4048-9cf6-9b1560de2dd5

Hi, here is some user feedback how that would work even better:
1. Please change "Videos" to "Join Online Event" and move it to the right of the page. Adjust the link to work with the token to access the video page. If the user does not have a ticket, show the message "Please get a ticket to join the online event."
2. Create a dropdown menu with 
2a. "Get Tickets" (which directs to the ticket page itself) and 
2b. "My Orders" (which directs to the accounts page with the orders list, e.g. https://wikimania-tickets.eventyay.com/wikiorg/account/)
2c. Please choose a suitable ticket icon

**Comment by it-tma-tri** [comment]
add-options-to-ticket-button
Dropdown options added as requested

**Review by mariobehling — CHANGES_REQUESTED** [review]
Previously the name of the event organiser was changed. Now that we have the drop-down menu the old name of the organiser is linked.

* It links to: https://tickets-dev.eventyay.com/eventyay-team/account
* Expected is that if the user is not logged in it should link to: https://tickets-dev.eventyay.com/conferenceorganiser/account/login?next=/conferenceorganiser/wikimania-test/ and if the user us logged in https://tickets-dev.eventyay.com/conferenceorganiser/account

I am not clear why the old name suddenly appears again.

Screenshot from 2024-07-30 17-00-12

**Comment by mariobehling** [comment]
Could you please split the PR into two PRs? 
PR 1: The change of the center and scroll area.
PR 2: The change of the menu.

Reason is I need to test PR 1 in more detail.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
