### PR TITLE
Remove mariadb support

### PR DESCRIPTION
**Pull request by AviGawande**
This PR fixes the issue #155 Though the existing version of python 3.8 is there to development branch , @norbusan should we update to 3.9/3.10 version

### CODE REVIEW

**Comment by norbusan** [comment]
THis PR contains the removal of MariaDB support, but ALSO the UA change, and some other unrelated, and adds requirements.txt files.

Can you please separate the PRs, thanks!

**Comment by norbusan** [comment]
And yes, update to Python 3.10 or 3.11 or even 3.12 would be good
I wouldn't bother going to 3.9.

**Comment by AviGawande** [comment]
thanks @norbusan i will update those changes.

**Comment by AviGawande** [comment]
i think updating the python to latest 3.9/3.10/3.11 version should a separate issue and worked separately.As the django is updated to 4.2 but on some scripts there is python 3.8 working.

**Comment by mariobehling** [comment]
Correct. Please keep Python and other issues separated. Just solve one thing in one PR. There can be exceptions, but they are seldom.

**Comment by AviGawande** [comment]
> Correct. Please keep Python and other issues separated. Just solve one thing in one PR. There can be exceptions, but they are seldom.

thats true,i think the python for eventyay-tickets has not been updated to 3.10,3.12 version for that should i create a new issue for it

**Comment by mariobehling** [comment]
@AviGawande Please keep the conversation focused and focus on the task at hand. Just finalize your issues for now. We can always follow up later about other questions.

**Comment by mariobehling** [comment]
Please resolve conflicts and finalize the PR.

**Comment by AviGawande** [comment]
resolved the conflicts

**Comment by hongquan** [comment]
@AviGawande You still don't remove the _requirements.txt_ (as Norbert requested). The dependencies are already listed in _pyproject.toml_ file. Don't create duplicate source.

**Comment by AviGawande** [comment]
> @AviGawande You still don't remove the _requirements.txt_ (as Norbert requested). The dependencies are already listed in _pyproject.toml_ file. Don't create duplicate source.

will remove requirements.txt and update the branch

**Review by hongquan — CHANGES_REQUESTED** [review]
@AviGawande The _development_ branch is already pinned with Python 3.11. Your PR should not downgrade it.

**Comment by AviGawande** [comment]
> @AviGawande The _development_ branch is already pinned with Python 3.11. Your PR should not downgrade it.

sure,will revert those changes.

**Review by hongquan — APPROVED** [review]

**Pull request merged**
