### PR TITLE
Removing mariadb support (Issue #29)

### PR DESCRIPTION
**Pull request by Kaushik-Iyer**
Attempts to solve and close Issue #29. Open to suggestions and changes since I am not quite sure of the code changes

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Before this PR can be merged a PostgreSQL related PR needs to be solved first here https://github.com/fossasia/eventyay-tickets/issues/28

**Comment by Kaushik-Iyer-skima** [comment]
@mariobehling is the postgresql PR identical to https://github.com/pretix/pretix/pull/3435/files? If yes then I shall attempt to solve that too

**Comment by Kaushik-Iyer** [comment]
@mariobehling  is the postgresql PR identical to https://github.com/pretix/pretix/pull/3435/files? If yes then I shall attempt to solve that too

**Comment by mariobehling** [comment]
> @mariobehling is the postgresql PR identical to https://github.com/pretix/pretix/pull/3435/files? If yes then I shall attempt to solve that too

It is correct that we need to achieve the same outcome, but as Pretix changed the license we cannot just copy changes. Of course changes that follow the documentation of MariaDB or PostgreSQL would be ok, but other changes would have to be implemented independently in order not to infringe other licenses.

**Comment by mariobehling** [comment]
Please make a new PR against the development branch. Closing this therefore. Thanks for your contribution.

**Pull request closed without merging**
