### PR TITLE
 Change default settings for background color, invoice attachments and name scheme #32

### LINKED ISSUE #32: Change default settings for background color, invoice attachments and name scheme
Change default settings for background color, invoice attachmentes and name scheme.

The goal of this PR to introduce straight forward changes similar to the PR in the original Pretix project here https://github.com/pretix/pretix/pull/2288/files

### PR DESCRIPTION
**Pull request by himanshugupta11002**
Fixes #32 
Changed default settings for background color , invoice attachments and name scheme

### CODE REVIEW

**Review by DaSeeker67 — APPROVED** [review]

**Comment by himanshugupta11002** [comment]
@mariobehling @hpdang Hello, I am eager to join GSOC-2024 with FOSSASIA and plan to submit a proposal for one of the eventyay ideas. I have already begun exploring the codebase of open-event-server and eventyay-tickets, and I'm actively working on addressing other issues. I would appreciate guidance on any additional steps I should take.

Additionally, I'm curious if you could review my pull request.

**Comment by mariobehling** [comment]
Thanks for your contribution. Please resolve merge conflicts. Yes, it would be great to get a proposal from you in GSoC.

**Comment by mariobehling** [comment]
Please make a PR against the development branch. Thanks

**Comment by mariobehling** [comment]
Please make this PR against the development branch. Closing it for now.

**Pull request closed without merging**
