### PR TITLE
change system branding of eventyay-tickets

### PR DESCRIPTION
**Pull request by AviGawande**
This PR fixed the issue #103 and  updates the remaining changes in the eventyay-tickets.As this issue was closed earlier and can't be merged into the existing PR of other contributor that why had to create a new PR on it.
here is the output
Screenshot (4)

### CODE REVIEW

**Comment by mariobehling** [comment]
505 files changed? You probably need to rebase before making this PR.

**Comment by AviGawande** [comment]
rebased the branch.should i had to raise another PR for this

**Comment by mariobehling** [comment]
You can see yourself that a PR of 505 files does not make sense. Please try to resolve this.

**Comment by AviGawande** [comment]
ok i will resolve it

**Pull request closed without merging**
